language: perl
perl:
    - "5.22"
    - "5.24"
before_install:
    - cpanm -n Devel::Cover::Report::Kritika
install:
    - cpanm -n -q --with-recommends --skip-satisfied --installdeps .
script:
    - perl Build.PL && ./Build build && cover -test -report kritika
